package Agentes;

public enum Estados {
    DESCANSANDO, SALUDANDO, PLATICANDO, POSANDO, DESPIDIENDOSE,
    ESPERANDOCLIENTE, MOSTRANDO, COBRANDO, ENVOLVIENDO, ENTREGANDO,
    PASEANDO, ESPERANDOSANTA, CONVIVIENDO, VIENDOREG, ESCOGIENDOREG, PAGANDO,
    MUERTO, PANICO, ESPERANDOENVOLTURA
}
