package Agentes;

enum Estados {
    DESCANSANDO, SALUDANDO, PLATICANDO, POSANDO, DESPIDIENDOSE,
    ESPERANDOCLIENTE, MOSTRANDO, COBRANDO, ENVOLVIENDO, ENTREGANDO,
    PASEANDO, ESPERANDOSANTA, CONVIVIENDO, BUSCANDOREG, COMPRANDO, PAGANDO
}
