package Agentes;

enum Estados {
    DESCANSANDO, SALUDANDO, PLATICANDO, POSANDO, DESPIDIENDOSE,
    ESPERANDO, VENDIENDO, COBRANDO, ENVOLVIENDO,
    PASEANDO, CONVIVIENDO, BUSCANDOREG, COMPRANDO, PAGANDO
}
